### ISSUE TITLE
Open iviewer page using sessionid instead of going through login page

### ISSUE THREAD

**Issue by kyxyes** [ome/omero-iviewer#197]
Hi,
We are working on a project using SSO and want a link to redirect to iviewer without requesting user to input at login page again.
According to this https://docs.openmicroscopy.org/omero/5.4.1/sysadmins/public.html?highlight=bsession#reusing-omero-session, If it is possible to open iviewer link by giving sessionid like  this?
`https://omero-sample-site.com/iviewer/?images=2&dataset=2?server=SERVER_ID&bsession=OMERO_SESSION_KEY`

**Comment by will-moore** [comment]
Yes, that should work just fine. If your OMERO.web is only configured to use one server (default config) you can omit the SERVER_ID, e.g.
```
https://omero-sample-site.com/iviewer/?images=2&dataset=2&bsession=OMERO_SESSION_KEY
```

**Comment by kyxyes** [comment]
@will-moore  Hi Thanks, I tried https://omero-sample-site.com/iviewer/?images=2&dataset=2&bsession=OMERO_SESSION_KEY, it keep redirecting me to login page. The OMERO_SESSION_KEY is generated by omero login api and it works for render_thumbnail. Do you know what issue it might be?

**Comment by will-moore** [comment]
Apologies for the delay in replying. I'm afraid I can't think of a reason that this works for ```render_thumbnail``` and not for the iviewer.
The ```bsession``` key is [read in the same way](https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/tools/OmeroWeb/omeroweb/decorators.py#L365) in the ```login_required``` decorator in the same way for both.
 
Do you have public user configured on your OMERO.web installation, allowing some urls to be accessed?
Are you sure that the session key hasn't timed out when you've used it for iviewer?

**Comment by kyxyes** [comment]
@will-moore  Thanks, finally I saw what is the issue, at my Chrome incognito page, I found the first time when I put `https://omero-sample-site.com/iviewer/?images=2&dataset=2&bsession=OMERO_SESSION_KEY`, it will redirect to login page. While if I put this same url again at same browser tab, then I can see the iviewer page with images without going through login page. This scenario looks like is same with render_thumbnail and image viewer. How could I be able to see the iviewer without enter this url twice?

**Comment by will-moore** [comment]
I've reproduced the bug you're seeing. I missed it before because I tried without ```?bsession``` key first, then with it, which worked OK since it wasn't the first request. So it seems the ```?bsession``` key joining session only works if there is an existing browser session.
However I'm on holiday just now so I might not have time to investigate for a few days, unless someone else on the team manages.

**Comment by waxenegger** [comment]
I'm speculating but it could be the browser session cookie is not set until the login view is hit which returns the Set-Cookie header which would explain why it works for consecutive requests. If that is the case I don't have any ideas for quick/easy/good fixes. The header has to be set and returned server side.

I'm very hesitant to even suggest an interims page that does nothing more than send an ajax request to the desired url to then redirect to it once done. It seems like an awful hack to me and bad user experience too, being redirected twice.

**Comment by waxenegger** [comment]
ok, I can definitely confirm my suspicion using the web-api in combination with curl. Prior to the sessionid cookie being set things will not work which is very reasonable in terms of security. The bsession parameter will not do away with that requirement.

**Comment by waxenegger** [comment]
@kyxyes I'm not sure if this is useful/plausible but I wonder if an additional web server tweak/'proxying' depending on some sensible condition (e.g. the origin of the single sign on?) can affect another redirect to the url you'd like to go. The browser receiving the redirect will set the cookie and then forward to the page which should not give you the login redirect any more since it has the session id by then.

**Comment by kyxyes** [comment]
@waxenegger It sounds like a solution. I can try as you said. Thanks for you guys help!!
