### ISSUE TITLE
Show ROIs "Pins" in iViewer

### ISSUE THREAD

**Issue by c15mnw** [ome/omero-iviewer#220]
It would be very useful to provide a tool within the viewer to aid the discovery of ROIs.

This could work in 2 ways:

1. Proximity: Moving the mouse across an image should cause ROIs to be "highlighted", when the mouse is near to a ROI - a "pin" would then appear (a la Google Maps), allowing the user to click to it, to show the ROI in the list on the RHS.  This functionality could be switched on and off as a viewer preference.
(This functionality would help as Point ROIs, in particular, are very difficult to locate within the image)

2. Individual ROI: Clicking on a ROI on the RHS, should cause the ROI within the image to be indicated by producing a "Pin" on the image.

Similar functionality is used in the eMouseatlas Histology
( https://www.emouseatlas.org/eAtlasViewer_ema/application/ema/kaufman/plate_38c.php?image=b )
( https://www.emouseatlas.org/emap/about/what_is_eHistology.html )

**Comment by will-moore** [comment]
These features (https://github.com/ome/omero-iviewer/pull/248) were included in the 0.8.0 release of iviewer 
https://www.openmicroscopy.org/2019/08/21/iviewer-0-8-0.html
(0.8.1 is the latest now).
