### ISSUE TITLE
Strange Z slice number display.

### ISSUE THREAD

**Issue by iandobbie** [ome/omero-iviewer#235]
If you open a Z stack in the viewer the Z display has a control region with a vertical stack of the total number of slices at the top, an up arrow, the slider, a down arrow then the current slice, an Z-slice icon, play arrow and the letter Z.

The fact the top is labeled with the maximum Z slice but the bottom with the current slice is a bit strange. If you move to the top slice you end up with a slider labeled at the top and bottom with the same number, which direction does the stack go in? I think the design needs to have 1 at the bottom and max Z at the top and then the current slice somewhere slightly different, maybe the Z label should be replaced with Z:Slice, like the floating indicator as you move the slider in Z?

**Comment by will-moore** [comment]
Thanks for the feedback. The design of the sliders is quite constrained by space, so we didn't feel there was room for ```Z: Slice``` there, particularly if there were > 100 or more slices.

<img width="95" alt="screen shot 2019-02-14 at 05 41 28" src="https://user-images.githubusercontent.com/900055/52765320-80859880-301b-11e9-82c6-78a15fa33556.png">

We were heavily influenced by the layout of the nice Icy tool, which uses the same strategy
e.g. http://icy.bioimageanalysis.org/images/11.jpg

I appreciate that a "static" view of the slider with the Z at the maximum slice is confusing. We would hope that in usage it becomes clearer what the various labels mean. Unfortunately the space limitations mean that a constant label of ```1``` is a luxury we can't afford. 

Hope that makes sense and thanks for feedback.

**Comment by iandobbie** [comment]
Yes I see you point, and I assumed as much but the current design can be quite confusing. However, I'm not sure I can think of a better one!
