### ISSUE TITLE
Download entire image stack for 3D-4D samples [suggestion]

### ISSUE THREAD

**Issue by tsloan1377** [ome/omero-iviewer#267]
I would like to be able to download an entire image stack for 3D images, but don't seem to be able. In the attached screenshot, it shows that the image has 988 Z-sections, but when I 'Export as TIFF' I can only download a single slice. 
![image](https://user-images.githubusercontent.com/26436062/57721102-56129e00-7651-11e9-9dcb-9b2ecca6fb75.png)

**Comment by will-moore** [comment]
Hi,
 The regular webclient has an option to run a Batch_Image_Export script (builds a zip file with multiple tiffs in it), but it looks like you're looking at IDR which doesn't allow public users to run scripts.
One option is to use your command line to download planes as tiffs:
You can specify the Z and T index in the URL (NB these are zero-based so will be off by 1 from what you see in the image viewer at https://idr.openmicroscopy.org/webclient/img_detail/4007801/)
Since this is a large image with a lot of Z and T planes, I would try to only download what you need. E.g. it seems that the default T index is 265 (266 in the viewer) and the Z planes are black at ```z: 0-255``` so to
to loop through the first few Z planes, starting at 256:
```
t=265
for (( z=256; z<260; z++ ))
do
  curl https://idr.openmicroscopy.org/webclient/render_image_download/4007801/$z/$t/?format=tif > imageZ$z-T$t.tif
done

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.7M  100 12.7M    0     0  2847k      0  0:00:04  0:00:04 --:--:-- 2847k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.7M  100 12.7M    0     0  3249k      0  0:00:04  0:00:04 --:--:-- 3250k
...
```

Hope that helps,

  Will.

**Comment by will-moore** [comment]
NB: That will download the image rendered as an ```8-bit``` tiff with the currently saved rendering settings. This doesn't give you the raw pixel values which are ```uint16``` for this image.

**Comment by tsloan1377** [comment]
Thanks so much, it works like a charm. 
I did it in Python with requests package:

```
t = 265 # Select one timepoint.
for z in range(255,260):

    # Create the relevant string
    this_url = ' https://idr.openmicroscopy.org/webclient/render_image_download/4007801/'+str(z)+'/'+str(t)+'/?format=tif' 

    # https://idr.openmicroscopy.org/webclient/render_image_download/4007801/256/265/?format=tif
    # Download and process the data
    filename = 't_'+ str(t) + '_z_' + str(z) + '.tif'
    # Verify if file already exists.
    if not os.path.exists(dl_path+filename):

        r = requests.get(this_url, allow_redirects=True)

        if not(r.status_code == 404):
            open(dl_path+filename, 'wb').write(r.content)
            print(str(datetime.datetime.now()) + ': Successfully downloaded file at: ' + this_url)
           
```

2019-05-16 11:06:01.676367: Successfully downloaded file at:  https://idr.openmicroscopy.org/webclient/render_image_download/4007801/255/265/?format=tif
2019-05-16 11:08:33.155809: Successfully downloaded file at:  https://idr.openmicroscopy.org/webclient/render_image_download/4007801/256/265/?format=tif
2019-05-16 11:11:59.057295: Successfully downloaded file at:  https://idr.openmicroscopy.org/webclient/render_image_download/4007801/257/265/?format=tif
2019-05-16 11:16:44.259243: Successfully downloaded file at:  https://idr.openmicroscopy.org/webclient/render_image_download/4007801/258/265/?format=tif

**Comment by tlskillman** [comment]
Thanks so much. Great help.  I tweaked the code to download a sequence of 3D image stacks, which I then reconstructed using ImageJ's Bio_Importer plugin.

import os
import requests
import datetime

dl_path = ""  # download path to store the files
for t in range(0,72,7):  # time steps 
  for z in range(0,8):  # z depth steps

    # Create the relevant string
    this_url = ' https://idr.openmicroscopy.org/webclient/render_image_download/9036344/'+str(z)+'/'+str(t)+'/?format=tif'

    # https://idr.openmicroscopy.org/webclient/render_image_download/4007801/256/265/?format=tif
    # Download and process the data
    filename = 't_'+ str(t) + '_z_' + str(z) + '.tif'
    # Verify if file already exists.
    if not os.path.exists(dl_path+filename):

        r = requests.get(this_url, allow_redirects=True)

        if not(r.status_code == 404):
            open(dl_path+filename, 'wb').write(r.content)
            print(str(datetime.datetime.now()) + ': Successfully downloaded file at: ' + this_url)

**Comment by tlskillman** [comment]
Thanks so much. Great help. I tweaked the code to download a sequence of 3D image stacks, which I then reconstructed using ImageJ's Bio_Importer plugin.


[Download4D.pdf](https://github.com/ome/omero-iviewer/files/4291510/Download4D.pdf)
