### ISSUE TITLE
wrong group context in opening well's images

### ISSUE THREAD

**Issue by mtbc** [ome/omero-iviewer#270]
With our normal test user setup:

1. Identify a plate in `read-annotate-1` owned by `user-5`.
1. Log into OMERO.web as `user-3`.
1. Select the thumbnail of one of the plate's wells (top-center pane).
1. Use the "Open with..." icon to open in OMERO.iviewer.
1. FAIL: See "No Image Data".

**Comment by mtbc** [comment]
Damir reports this bug also occurs with one's own data outside one's default group.

**Comment by will-moore** [comment]
Fixed in https://github.com/ome/omero-iviewer/pull/271

**Comment by mtbc** [comment]
This isn't working for me at all in Firefox or Chromium, I just get a blank tab (with a correct title) and `TypeError` stuff in the JavaScript console.
