### ISSUE TITLE
multiview channels off

### ISSUE THREAD

**Issue by jburel** [ome/omero-iviewer#290]
* Open 2 images in multiview
* Synch z/t and channels. 
* Turn off all channels on one image
* Turn them back on, The second image remains black
<img width="1307" alt="viewer1" src="https://user-images.githubusercontent.com/1022396/68677272-b9737f00-0553-11ea-96d4-6a858e9cba2c.png">

**Comment by will-moore** [comment]
The settings are simply set with the 'start' too high for that first image. When you sync the channels with the 2nd image, it is much brighter, so the settings are much higher. All the pixels in the 1st image are darker than the darkest pixel of the 2nd image.
Try it with 2 similar images and you won't see a problem.
