### ISSUE TITLE
Direct links to ROIs

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-iviewer#308]
* From the viewer, users should be able to copy a ROI url link.
 * A user going to that link should preferably see the same view as the user sending the link, i.e. viewer

**Comment by will-moore** [comment]
Need to consider the behaviour we want in more detail (See discussion at #311).
I think the handling of a single ROI is easier:

 - Select a single ROI -> click link button -> copy link like /iviewer/?rois=1 (or single ?roi=1)
 - This link opens the image that contains the ROI and selects the ROI
 - Left-hand thumbnails show the same as if we'd opened the image itself /iviewer/?images=1 (shows Dataset thumbnails or Well thumbnails or nothing if in multiple Datasets or orphaned).

How to handle selection of multiple ROIs is harder:

 - Do we even support this?
 - Do we allow ROIs from different images?
 - How do we allow you to browse between the chosen ROIs?
 - What is the maximum number we support?

cc @jburel @sbesson @pwalczysko

**Comment by will-moore** [comment]
As discussed today: 

 - initial support will be for a single ROI or shape only
 - Selecting a shape in iviewer -> copy link -> `/iviewer/?shape=1`
 - Handle `/iviewer/?shape=1` URL -> open image and select specified shape
 - Handle `/iviewer/?roi=1` -> open image and select first shape in ROI
 - Also look at supporting zoom if possible: Auto zoom to bounding box (and/or include zoom in copied link)
