### ISSUE TITLE
opening images in a share

### ISSUE THREAD

**Issue by juliomateoslangerak** [ome/omero-iviewer#324]
I'm in OMERO-web 5.5 and iViewer 0.8.1 so I do not know if this issue has been fixed meanwhile.

When I double click on an image in a share the iViewer window opens but I get no images to view. I would expect to have a view of the share, as if it was a dataset. 
I should have access to see the data and viewing the data in the preview panel on the left of the main web client is working fine.

**Comment by jburel** [comment]
Hi Julio

thanks for the comment, shares have been deprecated since 5.3 see https://help.openmicroscopy.org/sharing-data.html#share
We are not testing and working on making the new compatible with shares e.g. viewer, figure etc.
Closing this issue.
