### ISSUE TITLE
BUG: Opening well sample

### ISSUE THREAD

**Issue by jburel** [ome/omero-iviewer#345]
While preparing data for testing another PR, I selected a well sample with 180 timepoints (problem not related to the number of timepoints).
The viewer is stuck in the ``Loading Image Data`` state

cc @will-moore

**Comment by will-moore** [comment]
Currently this is working (loads Well thumbnails):
https://merge-ci.openmicroscopy.org/web/webclient/img_detail/105293/
and opening the Well directly works:
https://merge-ci.openmicroscopy.org/web/iviewer/?well=23254

Can you point me at a Well where it's not working?

**Comment by jburel** [comment]
It seems to be loading now.
It might have been very slow this am. 
I will re-open if required
