### ISSUE TITLE
Lack of license file

### ISSUE THREAD

**Issue by andor-pierdelacabeza** [ome/omero-iviewer#362]
Other ome repositories have a LICENSE file specifying the project license.
I can't see it here so I'm not sure if it's GPLv2 as some of the other repos.
Could it be included?

Thanks!

**Comment by jburel** [comment]
There is a license file. 
Due to the layout of this repositories it is probably not where you were expecting it
https://github.com/ome/omero-iviewer/blob/master/plugin/LICENSE
