### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by CamachoDejay** [ome/omero-iviewer#407]
Hej,

This is just a small recommendation for the [documentation of the installation procedure](https://github.com/ome/omero-iviewer/blob/master/plugin/omero_iviewer/README.rst). It might be very obvious after you are working with OMERO for a while but not so much at the beginning. I would add that the installation of the omero-iviewer should be done from root using the pip of the OMERO.web venv. Something along the lines:

Run as root:
$VENV_WEB/bin/pip install -U omero-iviewer  
where in my case the VENV_WEB=/opt/omero/web/venv3

Then just add that all other steps are done from the omero-web user.

Best regards,
Rafa

**Comment by jburel** [comment]
Thanks for the feedback 
We will add that to our documentation
The same will apply to all the other app e.g. omero-figure
