### ISSUE TITLE
Open maximised view as default

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-iviewer#480]
Mentioned in https://forum.image.sc/t/omero-web-configuration/98844

Open the full-screen image as default when clicking on thumbnail in omero-web. Possibly can be treated as a subtopic under the [iviewer settings issue](https://github.com/ome/omero-iviewer/issues/282) ?

**Comment by Jcarlosmiguel** [comment]
The issue is relevant when public images are used in a virtual learning environment for teaching and there is no need of set up distraction, only the browser image
